class RandomDataset {
    RANDOM_USER_LIST = [ 
                            {Name: 'Rogelio Barton', Email: 'rogelio.barton@training.com'}, {Name: 'Ernestine Dawson', Email: 'ernestine.dawson@training.com'}, 
                            {Name: 'Katrina Pope', Email: 'katrina.pope@training.com'}, {Name: 'Laura Houston', Email: 'laura.houston@training.com'},
                            {Name: 'Jermaine Gross', Email: 'jermaine.gross@training.com'}, {Name: 'Randall Sherman', Email: 'randall.sherman@training.com'},
                            {Name: 'Charlene Mendez', Email: 'charlene.mendez@training.com'}, {Name: 'Sue Chavez', Email: 'sue.chavez@training.com'},
                            {Name: 'Allison Myers', Email: 'allison.myers@training.com'}, {Name: 'Pete Wilkerson', Email: 'pete.wilkerson@training.com'},
                            {Name: 'Tami Perry', Email: 'tami.perry@training.com'}, {Name: 'Julie Bennett', Email: 'julie.bennett@training.com'},
                            {Name: 'Steven Erickson', Email: 'steven.erickson@training.com'}, {Name: 'Jeannie Rios', Email: 'jeannie.rios@training.com'}, 
                            {Name: 'Nathaniel Ellis', Email: 'nathaniel.ellis@training.com'},
                            {Name: 'Phil Colon', Email: 'phil.colon@training.com'},
                            {Name: 'Darrel Hart', Email: 'darrel.hart@training.com'},
                            {Name: 'Jenny Bush', Email: 'jenny.bush@training.com'},
                            {Name: 'Joann Tyler', Email: 'joann.tyler@training.com'},
                            {Name: 'Craig Higgins', Email: 'craig.higgins@training.com'},
                            {Name: 'Randolph Grant', Email: 'randolph.grant@training.com'},
                            {Name: 'Jody Baldwin', Email: 'jody.baldwin@training.com'},
                            {Name: 'Harry Harper', Email: 'harry.harper@training.com'},
                            {Name: 'Randy Hernandez', Email: 'randy.hernandez@training.com'},
                            {Name: 'Chester Sullivan', Email: 'chester.sullivan@training.com'},
                            {Name: 'Sherry Love', Email: 'sherry.love@training.com'},
                            {Name: 'Doyle Moore', Email: 'doyle.moore@training.com'},
                            {Name: 'Percy Medina', Email: 'percy.medina@training.com'},
                            {Name: 'Agnes Austin', Email: 'agnes.austin@training.com'},
                            {Name: 'Alton Stone', Email: 'alton.stone@training.com'},
                            {Name: 'Albert Barrett', Email: 'albert.barrett@training.com'},
                            {Name: 'Isabel Schultz', Email: 'isabel.schultz@training.com'},
                            {Name: 'Tricia Jensen', Email: 'tricia.jensen@training.com'},
                            {Name: 'Delia Gonzalez', Email: 'delia.gonzalez@training.com'},
                            {Name: 'Isaac Wallace', Email: 'isaac.wallace@training.com'},
                            {Name: 'Janice Lawson', Email: 'janice.lawson@training.com'},
                            {Name: 'Howard Coleman', Email: 'howard.coleman@training.com'},
                            {Name: 'Nathan Holloway', Email: 'nathan.holloway@training.com'},
                            {Name: 'Lana Torres', Email: 'lana.torres@training.com'},
                            {Name: 'Glen Bowen', Email: 'glen.bowen@training.com'},
                            {Name: 'Lori Butler', Email: 'lori.butler@training.com'},
                            {Name: 'Evelyn Ortega', Email: 'evelyn.ortega@training.com'},
                            {Name: 'Perry Cunningham', Email: 'perry.cunningham@training.com'},
                            {Name: 'Claudia Thompson', Email: 'claudia.thompson@training.com'},
                            {Name: 'Silvia Cooper', Email: 'silvia.cooper@training.com'},
                            {Name: 'Margarita Cross', Email: 'margarita.cross@training.com'},
                            {Name: 'Joanna Romero', Email: 'joanna.romero@training.com'},
                            {Name: 'Rudy Barker', Email: 'rudy.barker@training.com'},
                            {Name: 'Erika Santos', Email: 'erika.santos@training.com'},
                            {Name: 'Abel Klein', Email: 'abel.klein@training.com'},
                            {Name: 'Melissa Phillips', Email: 'melissa.phillips@training.com'},
                            {Name: 'Rodolfo Harmon', Email: 'rodolfo.harmon@training.com'},
                            {Name: 'Lynne Crawford', Email: 'lynne.crawford@training.com'},
                            {Name: 'Benny Perez', Email: 'benny.perez@training.com'},
                            {Name: 'Delbert Richards', Email: 'delbert.richards@training.com'},
                            {Name: 'Robin Murray', Email: 'robin.murray@training.com'},
                            {Name: 'Clarence Rivera', Email: 'clarence.rivera@training.com'},
                            {Name: 'Sonya Ruiz', Email: 'sonya.ruiz@training.com'},
                            {Name: 'Sylvester Norris', Email: 'sylvester.norris@training.com'},
                            {Name: 'Darryl Vaughn', Email: 'darryl.vaughn@training.com'},
                            {Name: 'Javier Simpson', Email: 'javier.simpson@training.com'},
                            {Name: 'Elias Ray', Email: 'elias.ray@training.com'},
                            {Name: 'Neil Ryan', Email: 'neil.ryan@training.com'},
                            {Name: 'Corey Richardson', Email: 'corey.richardson@training.com'},
                            {Name: 'Billie Frazier', Email: 'billie.frazier@training.com'},
                            {Name: 'Jim Moss', Email: 'jim.moss@training.com'},
                            {Name: 'Johnny Maxwell', Email: 'johnny.maxwell@training.com'},
                            {Name: 'Doug Taylor', Email: 'doug.taylor@training.com'},
                            {Name: 'Mattie Powell', Email: 'mattie.powell@training.com'},
                            {Name: 'Tommie Walsh', Email: 'tommie.walsh@training.com'},
                            {Name: 'Alison Clayton', Email: 'alison.clayton@training.com'},
                            {Name: 'Melba Mcbride', Email: 'melba.mcbride@training.com'},
                            {Name: 'Bridget Daniels', Email: 'bridget.daniels@training.com'},
                            {Name: 'Samuel Ward', Email: 'samuel.ward@training.com'},
                            {Name: 'Cody Ball', Email: 'cody.ball@training.com'},
                            {Name: 'Emma Reyes', Email: 'emma.reyes@training.com'},
                            {Name: 'Sylvia Washington', Email: 'sylvia.washington@training.com'},
                            {Name: 'Estelle Owen', Email: 'estelle.owen@training.com'},
                            {Name: 'Carlton Jordan', Email: 'carlton.jordan@training.com'},
                            {Name: 'Gregory Page', Email: 'gregory.page@training.com'},
                            {Name: 'Madeline Riley', Email: 'madeline.riley@training.com'},
                            {Name: 'Dawn Burke', Email: 'dawn.burke@training.com'},
                            {Name: 'Marvin Olson', Email: 'marvin.olson@training.com'},
                            {Name: 'Ivan Caldwell', Email: 'ivan.caldwell@training.com'},
                            {Name: 'Dana Griffith', Email: 'dana.griffith@training.com'},
                            {Name: 'Dexter Bowman', Email: 'dexter.bowman@training.com'},
                            {Name: 'Garry May', Email: 'garry.may@training.com'},
                            {Name: 'Sherri Nichols', Email: 'sherri.nichols@training.com'},
                            {Name: 'Wesley Fisher', Email: 'wesley.fisher@training.com'},
                            {Name: 'Myron Obrien', Email: 'myron.obrien@training.com'},
                            {Name: 'Cecil Wright', Email: 'cecil.wright@training.com'},
                            {Name: 'Melody Allison', Email: 'melody.allison@training.com'},
                            {Name: 'Kay Fuller', Email: 'kay.fuller@training.com'},
                            {Name: 'Ted Stevens', Email: 'ted.stevens@training.com'},
                            {Name: 'James Rice', Email: 'james.rice@training.com'},
                            {Name: 'Daniel Arnold', Email: 'daniel.arnold@training.com'},
                            {Name: 'Jesse Woods', Email: 'jesse.woods@training.com'},
                            {Name: 'Cecilia Mccoy', Email: 'cecilia.mccoy@training.com'},
                            {Name: 'Leland Adkins', Email: 'leland.adkins@training.com'},
                            {Name: 'Austin Thomas', Email: 'austin.thomas@training.com'},
                            {Name: 'Eduardo Moss', Email: 'eduardo.moss@training.com'},
                            {Name: 'Betsy Hale', Email: 'betsy.hale@training.com'},
                            {Name: 'Wallace Henry', Email: 'wallace.henry@training.com'},
                            {Name: 'Mabel Hawkins', Email: 'mabel.hawkins@training.com'},
                            {Name: 'Alicia Allison', Email: 'alicia.allison@training.com'},
                        ]
}

export default new RandomDataset()